version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/project/did-medical-record-management

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
